from enum import Enum

class MessageEnum(Enum):
    LOGIN_SUCCESS = 'Login successful'
    LOGIN_FAILED = 'Login failed'
    LOGOUT_SUCCESS = 'Token revoked successfully.'
    LOGOUT_FAILED = 'Logout failed'
    USERNAME_REQUIRED = 'Username is required.'
    PASSWORD_REQUIRED = 'Password is required.'
    TOKEN_REQUIRED = 'No token provided.'
    PRODUCT_LIST_SUCCESS = 'Product list fetched successfully.'
    PRODUCT_DETAIL_SUCCESS = 'Product details fetched successfully.'
    PRODUCT_NOT_FOUND = 'Product not found.'
    CART_LIST_SUCCESS = 'Cart list fetched successfully.'
    ADD_TO_CART_SUCCESS = 'Product added to cart successfully.'
    EDIT_CART_SUCCESS = 'Cart updated successfully.'
    REMOVE_CART_SUCCESS = 'Cart item removed successfully.'
    CART_NOT_FOUND = 'Cart item not found.'
    INSUFFICIENT_STOCK = 'Insufficient stock for this product.'
    PRODUCT_REQUIRED = 'Product is required.'
    QUANTITY_REQUIRED = 'Quantity is required.'
    QUANTITY_MIN_VALUE = 'Quantity must be at least 1.'
    ADD_TO_CART_FAILED = 'Failed to add product to cart.'
    EDIT_CART_FAILED = 'Failed to update cart.'
    INCREMENT_CART_SUCCESS = 'Cart item incremented successfully.'
    DECREMENT_CART_SUCCESS = 'Cart item decremented successfully.'
    DECREMENT_CART_FAILED = 'Cannot decrement cart item below 1.'
